// angular-ts/src/app/recipe-card/recipe-card.component.ts
import { Component, Input } from '@angular/core';
import { NgFor } from '@angular/common';

@Component({
  standalone: true,
  selector: 'app-recipe-card',
  templateUrl: './recipe-card.component.html',
  styleUrl: './recipe-card.component.css',
  imports: [NgFor],
})
export class RecipeCardComponent {
  @Input() name: string = '';
  @Input() ingredients: string[] = [];
}

<div class="recipe-card">
  <h2 class="recipe-card-title">{{ name }}</h2>
  <ul class="recipe-card-ingredients">
    <li *ngFor="let ingredient of ingredients">{{ ingredient }}</li>
  </ul>
</div>

// react-js/src/components/RecipeCard.jsx
import "./RecipeCard.css";

export const RecipeCard = ({ name, ingredients }) => {
  return (
    <div className="recipe-card">
      <h2 className="recipe-card-title">{name}</h2>
      <ul className="recipe-card-ingredients">
        {ingredients.map((ingredient) => (
          <li key={ingredient}>{ingredient}</li>
        ))}
      </ul>
    </div>
  );
};
