// ts-react/src/components/VisibilityButton.tsx
import { VisibilityOffIcon } from "./icons/VisibilityOffIcon";
import { VisibilityIcon } from "./icons/VisibilityIcon";
import "./VisibilityButton.css";

type VisibilityButtonProps = {
  isVisible: boolean;
  setIsVisible: (isVisible: boolean) => void;
};

export const VisibilityButton = ({
  isVisible,
  setIsVisible,
}: VisibilityButtonProps) => {
  return (
    <button
      className="visibility-button"
      type="button"
      onClick={() => setIsVisible(!isVisible)}
      aria-label={isVisible ? "Hide password" : "Show password"}
    >
      {isVisible ? <VisibilityOffIcon /> : <VisibilityIcon />}
    </button>
  );
};

// vue-js/src/components/VisibilityButton.vue
<template>
  <button
    class="visibility-button"
    type="button"
    @click="$emit('update:modelValue', !modelValue)"
    :aria-label="modelValue ? 'Hide password' : 'Show password'"
  >
    <VisibilityIcon v-if="modelValue" />
    <VisibilityOffIcon v-else />
  </button>
</template>

<script setup>
import VisibilityIcon from "./icons/VisibilityIcon.vue";
import VisibilityOffIcon from "./icons/VisibilityOffIcon.vue";

defineProps({
  modelValue: {
    type: Boolean,
    required: true,
  },
});
</script>

<style scoped>
.visibility-button {
  background-color: transparent;
  display: flex;
  height: 36px;
  width: 36px;
  justify-content: center;
  align-items: center;
  border: none;
}
</style>
