// js-vue/src/components/Dummy.vue
<template>
  <div class="dummy">
    <p>Counter value: {{ counter }}</p>
    <button @click="increment">Increment</button>
    <input v-model="text" placeholder="Type here" />
    <p>Text value: {{ text }}</p>
  </div>
</template>

<script setup>
import { ref } from "vue";

const counter = ref(0);
const text = ref("");

function increment() {
  counter.value++;
}
</script>

<style scoped></style>

// react-ts/src/components/Dummy.tsx
import { useState } from "react";

export const Dummy = () => {
  const [counter, setCounter] = useState(0);
  const [text, setText] = useState("");

  return (
    <div className="dummy">
      <p>Counter value: {counter}</p>
      <button onClick={() => setCounter(counter + 1)}>Increment</button>
      <input
        type="text"
        value={text}
        onChange={(event) => setText(event.target.value)}
        placeholder="Type here"
      />
      <p>Text value: {text}</p>
    </div>
  );
};
