// js-react/src/pages/Login.jsx
import { useEffect, useState } from "react";
import "./Login.css";
import { EmailField } from "../components/EmailField.jsx";
import { PasswordField } from "../components/PasswordField.jsx";
import { Title } from "../components/Title";
import { Button } from "../components/Button";
import { translateError } from "../utils/translateError.js";
import { useNavigate } from "react-router-dom";

export const Login = () => {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [errorMessage, setErrorMessage] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setErrorMessage(null);
  }, [email, password]);

  return (
    <main className="login-container">
      <form
        className="login-form"
        onSubmit={(event) => {
          event.preventDefault();
          setIsLoading(true);
          setErrorMessage(null);

          fetch("https://backend-login-placeholder.deno.dev/api/users/login", {
            method: "POST",
            body: JSON.stringify({ email, password }),
            headers: {
              "Content-Type": "application/json",
            },
          })
            .then((response) => response.json())
            .then((data) => {
              if (data.status === "error") {
                throw new Error(data.code);
              }
              return data.payload;
            })
            .then((payload) => {
              localStorage.setItem("token", payload.jwt);
            })
            .then(() => {
              navigate("/recipes");
            })
            .catch((error) => {
              setErrorMessage(error.message);
            })
            .finally(() => {
              setIsLoading(false);
            });
        }}
      >
        <Title>Login with email</Title>
        <p>Enter your email address to login with your account.</p>

        <EmailField
          id="email"
          labelText="Your email"
          value={email}
          onChange={setEmail}
        />
        <PasswordField
          id="password"
          labelText="Your password"
          value={password}
          onChange={setPassword}
        />
        {errorMessage && <p>{translateError(errorMessage)}</p>}
        <Button title="Login" disabled={isLoading} />
      </form>
    </main>
  );
};

// angular-ts/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent {
  email = '';
  password = '';
  isLoading = false;
  errorMessage = '';

  constructor(private readonly router: Router) {}

  async login() {
    return fetch('https://backend-login-placeholder.deno.dev/api/users/login', {
      method: 'POST',
      body: JSON.stringify({ email: this.email, password: this.password }),
      headers: {
        'Content-Type': 'application/json',
      },
    })
      .then((response) => response.json())
      .then((data) => {
        if (data.status === 'error') {
          throw new Error(data.code);
        }
        return data.payload;
      })
      .then((payload) => {
        localStorage.setItem('token', payload.jwt);
      })
      .then(() => {
        return this.router.navigateByUrl('/recipes');
      })
      .catch((error) => {
        this.errorMessage = error.message;
      })
      .finally(() => {
        this.isLoading = false;
      });
  }
}

<main class="login-container">
  <form [formGroup]="loginForm" (ngSubmit)="login()" class="login-form">
    <div>
      <app-email-field
        identifier="fooo"
        label="Your email"
        formControlName="email"
      />
    </div>
    <div>
      <app-password-field
        identifier="password"
        label="Your password"
        formControlName="password"
      />
    </div>
    <p *ngIf="errorMessage">{{ errorMessage }}</p>
    <button class="button-container">Login</button>
  </form>
</main>
