// js-vue/src/components/PasswordField.vue
<template>
  <div class="password-field-container">
    <label :for="id">{{ labelText }}</label>
    <input
      :id="id"
      type="password"
      :value="modelValue"
      @input="updateModelValue"
    />
  </div>
</template>

<script setup>
defineProps({
  modelValue: {
    type: String,
    required: true,
  },
  id: {
    type: String,
    required: true,
    default: "text",
  },
  labelText: {
    type: String,
    required: true,
    default: "text",
  },
});

const emit = defineEmits(["update:modelValue"]);

function updateModelValue(event) {
  emit("update:modelValue", event.target.value);
}
</script>

<style scoped>
.password-field-container {
  display: flex;
  flex-direction: column;
}

.password-field-container label {
  font-size: 14px;
}

.password-field-container input {
  height: 32px;
  border: none;
  border-bottom: 1px solid #474747;
}
</style>

// src/components/PasswordField.jsx
import "./PasswordField.css";

export const PasswordField = ({ id, labelText, value, onChange }) => {
  return (
    <div className="password-field-container">
      <label htmlFor={id}>{labelText}</label>
      <input
        id={id}
        type="password"
        value={value}
        onChange={(event) => onChange(event.target.value)}
      ></input>
    </div>
  );
};
