// js-react/src/pages/Login.jsx
import { useEffect, useState } from "react";
import "./Login.css";
import { EmailField } from "../components/EmailField.jsx";
import { PasswordField } from "../components/PasswordField.jsx";
import { Title } from "../components/Title";
import { Button } from "../components/Button";
import { translateError } from "../utils/translateError.js";
import { useNavigate } from "react-router-dom";

export const Login = () => {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [errorMessage, setErrorMessage] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setErrorMessage(null);
  }, [email, password]);

  return (
    <main className="login-container">
      <form
        className="login-form"
        onSubmit={(event) => {
          event.preventDefault();
          setIsLoading(true);
          setErrorMessage(null);

          fetch("https://backend-login-placeholder.deno.dev/api/users/login", {
            method: "POST",
            body: JSON.stringify({ email, password }),
            headers: {
              "Content-Type": "application/json",
            },
          })
            .then((response) => response.json())
            .then((data) => {
              if (data.status === "error") {
                throw new Error(data.code);
              }
              return data.payload;
            })
            .then((payload) => {
              localStorage.setItem("token", payload.jwt);
            })
            .then(() => {
              navigate("/recipes");
            })
            .catch((error) => {
              setErrorMessage(error.message);
            })
            .finally(() => {
              setIsLoading(false);
            });
        }}
      >
        <Title>Login with email</Title>
        <p>Enter your email address to login with your account.</p>

        <EmailField
          id="email"
          labelText="Your email"
          value={email}
          onChange={setEmail}
        />
        <PasswordField
          id="password"
          labelText="Your password"
          value={password}
          onChange={setPassword}
        />
        {errorMessage && <p>{translateError(errorMessage)}</p>}
        <Button title="Login" disabled={isLoading} />
      </form>
    </main>
  );
};

// js-vue/src/pages/Login.vue
<template>
  <main class="login-container">
    <form class="login-form" @submit.prevent="onSubmit">
      <Title>Login with email</Title>
      <p>Enter your email address to create an account.</p>

      <EmailField id="email" label-text="Your email" v-model="email" />
      <PasswordField
        id="password"
        label-text="Your password"
        v-model="password"
      />
      <p v-if="errorMessage">{{ translateError(errorMessage) }}</p>
      <Button title="Login" :disabled="isLoading" />
    </form>
  </main>
</template>

<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
import Title from "../components/Title.vue";
import EmailField from "../components/EmailField.vue";
import PasswordField from "../components/PasswordField.vue";
import Button from "../components/Button.vue";
import { translateError } from "../utils/translateError.js";

const router = useRouter();

const email = ref("");
const password = ref("");
const errorMessage = ref("");
const isLoading = ref(false);

function onSubmit() {
  isLoading.value = true;
  errorMessage.value = "";

  fetch("https://backend-login-placeholder.deno.dev/api/users/login", {
    method: "POST",
    body: JSON.stringify({ email: email.value, password: password.value }),
    headers: {
      "Content-Type": "application/json",
    },
  })
    .then((response) => response.json())
    .then((data) => {
      if (data.status === "error") {
        throw new Error(data.code);
      }
      return data.payload;
    })
    .then((payload) => {
      localStorage.setItem("token", payload.jwt);
    })
    .then(() => {
      router.push("/recipes");
    })
    .catch((error) => {
      errorMessage.value = error.message;
    })
    .finally(() => {
      isLoading.value = false;
    });
}
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  margin-top: 64px;
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 32px;
  padding: 32px;
  border-radius: 8px;
}

@media (min-width: 801px) {
  .login-form {
    box-shadow: rgb(0 0 0 / 15%) 0 2px 10px;
    padding: 64px;
  }
}
</style>
