// angular-ts/src/app/recipes/recipes.component.ts
import { Component, OnInit } from '@angular/core';
import { RecipeCardComponent } from '../recipe-card/recipe-card.component';
import { NgFor } from '@angular/common';

type Recipe = {
  id: string;
  name: string;
  ingredients: string[];
};

@Component({
  selector: 'app-recipes',
  standalone: true,
  imports: [RecipeCardComponent, NgFor],
  templateUrl: './recipes.component.html',
  styleUrl: './recipes.component.css',
})
export class RecipesComponent implements OnInit {
  recipes: Recipe[] = [];

  ngOnInit(): void {
    fetch('https://backend-login-placeholder.deno.dev/api/recepies', {
      headers: {
        Authorization: `Bearer ${localStorage.getItem('token')}`,
      },
    })
      .then((response) => response.json())
      .then((data) => {
        if (data.status === 'error') {
          throw new Error(data.code);
        }
        return data.payload;
      })
      .then((recipes) => {
        this.recipes = recipes;
      });
  }
}

<main class="recipes-page">
  <h1>Recipes</h1>
  <div class="recipes">
    <div *ngFor="let recipe of recipes">
      <app-recipe-card
        [name]="recipe.name"
        [ingredients]="recipe.ingredients"
      ></app-recipe-card>
    </div>
  </div>
</main>

// react-ts/src/pages/Recipes.tsx
import { useEffect, useState } from "react";
import { Title } from "../components/Title";
import { RecipeCard } from "../components/RecipeCard";
import "./Recipes.css";

type Recipe = {
  id: string;
  name: string;
  ingredients: string[];
};

export const Recipes = () => {
  const [recipes, setRecipes] = useState<Recipe[]>([]);

  useEffect(() => {
    fetch("https://backend-login-placeholder.deno.dev/api/recepies", {
      headers: {
        Authorization: `Bearer ${localStorage.getItem("token")}`,
      },
    })
      .then((response) => response.json())
      .then((data) => {
        if (data.status === "error") {
          throw new Error(data.code);
        }
        return data.payload;
      })
      .then((recipes) => {
        setRecipes(recipes);
      });
  }, []);

  return (
    <main className="recipes-page">
      <Title>Recipes</Title>
      <div className="recipes">
        {recipes.map((recipe) => (
          <RecipeCard
            name={recipe.name}
            ingredients={recipe.ingredients}
            key={recipe.id}
          />
        ))}
      </div>
    </main>
  );
};
