// js-react/src/components/EmailField.jsx
import "./EmailField.css";

export const EmailField = ({ id, labelText, value, onChange }) => {
  return (
    <div className="email-field-container">
      <label htmlFor={id}>{labelText}</label>
      <input
        id={id}
        type="email"
        value={value}
        onChange={(event) => onChange(event.target.value)}
      ></input>
    </div>
  );
};

// angular-ts/src/app/email-field/email-field.component.ts
import { Component, Input } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'app-email-field',
  standalone: true,
  imports: [],
  templateUrl: './email-field.component.html',
  styleUrl: './email-field.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: EmailFieldComponent,
      multi: true,
    },
  ],
})
export class EmailFieldComponent implements ControlValueAccessor {
  @Input() id!: string;
  @Input() label!: string;
  value = '';
  onChange!: (value: string) => void;

  changeText($event: any) {
    this.onChange($event.target.value);
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {}

  writeValue(obj: any): void {
    this.value = obj;
  }
}

<div class="email-field-container">
  <label [for]="id">{{ label }}</label>
  <input [id]="id" type="email" [value]="value" (input)="changeText($event)" />
</div>
